### ISSUE TITLE
CAD release date

### ISSUE THREAD

**Issue by Rudis1261** [Annex-Engineering/Gasherbrum-K3#11]
Hi Guys, loving building the printer so far, just waiting on the slow boat from China. 

Any idea when the CAD for the printer will be released? I am quite keen to create a hotend mount for my orbiter straight from source if possible. Along with some minor tweaks to suite my needs. 

Cheers

**Comment by Rudis1261** [comment]
For example, I am struggling to find the right size heat inserts, so would be nice to be able to modify those parts

**Comment by Annex-Engineering** [comment]
TLDR: we dont do cad releases on beta machines, theres a lot of reasons behind it, and it would take me 2 pages to cover them all

sadly, an orbiter will not fit on the K3, youll lose 20mm of x and y travel because of it. We highly recommend you use our extruders instead, as they are lighter and perform better.

Have you tried the sourcing guide for the heatsets?

**Comment by Rudis1261** [comment]
The heat set inserts on the sourcing guide (aliexpress) is very expensive to ship $130 just in shipping. It's a bit on the rough side.  So I am forced to edit the STL files which can be a tad painful, but I understand you have your reasons.

I have printed the Sherpa, and slapped in some bondtech gears in there, so hope to keep making progress on the build.

Any ETA (ballpark) on when the printer will come out of beta?

**Comment by Annex-Engineering** [comment]
we dont have an ETA for any release, we dont like putting timelines on things because it tends to create sloppy work (and its all a hobby for everyone here, so the last thing they need is to be stressed about it)

**Comment by Rudis1261** [comment]
Fair enough. Keep up the great work, cant wait to also have a working K3.

Really impression with your innovative design!
