### ISSUE TITLE
Screw Z part in common folder

### ISSUE THREAD

**Issue by Rudis1261** [Annex-Engineering/Gasherbrum-K3#16]
Hey guys, 

Can you please move this file:
https://github.com/Annex-Engineering/Gasherbrum-K3/blob/main/STLs/3Z_Drive_Components/common_parts/safety_spring_mount_rear_x1_rev2.stl 

To this folder?
https://github.com/Annex-Engineering/Gasherbrum-K3/tree/main/STLs/3Z_Drive_Components/tr12_screw_drive

It's for the screw z

**Comment by LeandroMarceddu** [comment]
#15
