### ISSUE TITLE
Humps that slot into alu extrusions do not match

### ISSUE THREAD

**Issue by amp-man** [Annex-Engineering/Gasherbrum-K3#22]
The little humps that fit into the alu extrusion slots are wider than the rest of the K3 parts.
The following parts that I found have the wider hump:
- front_door_bearing_block_1_x2_rev1.STL
- front_door_bearing_block_2_x2_rev1.STL
- front_door_magnet_catch_x1_rev1.STL
It would be great if you could make the hump of these parts smaller, e.g. make them the same as the rest of the parts.
The smaller hump seems to work fine for all other K3 Parts and have the benefit that they also work for I type 5mm extrusion.

**Comment by Trails5000** [comment]
added files with this commit: [e80344b860d09d5b334a637461350ae481a8b810](https://github.com/Annex-Engineering/Gasherbrum-K3/commit/e80344b860d09d5b334a637461350ae481a8b810)

**Comment by amp-man** [comment]
Thanks :)
