### ISSUE TITLE
5x8x1 washers missing in sourcing guide

### ISSUE THREAD

**Issue by Zaglim** [Annex-Engineering/Gasherbrum-K3#25]
Hi,

The sourcing guide has yet to have 5x8x1 washers in it. A filter search of "Washer, 5x8x1" in the eDrawing shows 12 such washers common to both configurations, and 12 more for the belt-Z config.
None unique to the screw config.

I hope this is the right place to let the Annex team know!

**Comment by Trails5000** [comment]
added, thanks
