### ISSUE TITLE
XY Endstop(X Max) incorrect size in CAD

### ISSUE THREAD

**Issue by jyoorepo** [Annex-Engineering/Gasherbrum-K3#42]
XY Endstop(X Max) screw shows "socket head cap screw_am(B18.3.1M - 3 x 0.5 x 45 Hex SHCS -- 18NHX)" but isn't this supposed to be m5x20mm?
<img width="946" alt="Screenshot 2023-06-08 at 9 09 26 PM" src="https://github.com/Annex-Engineering/Gasherbrum-K3/assets/94655070/75e63c84-ec42-4c36-b542-5faa54b3f3fe">

**Comment by PapeJelly** [comment]
Its fixed in the upcoming K3 manual 👍
