### ISSUE TITLE
Minor R1.2 STL issues

### ISSUE THREAD

**Issue by ruiqimao** [Annex-Engineering/Gasherbrum-K3#43]
A couple of issues I've found while printing parts:

- [[a]_xy_tensioner_moving_moar_grip_x8_rev1.stl](https://github.com/Annex-Engineering/Gasherbrum-K3/blob/main/Release_1_2/STLs/XY_Gantry/%5Ba%5D_xy_tensioner_moving_moar_grip_x8_rev1.stl) indicates that 8 copies should be printed. However, now that [[a]_z_tensioner_moving_moar_grip_x3_rev1.stl](https://github.com/Annex-Engineering/Gasherbrum-K3/blob/main/Release_1_2/STLs/3Z_Drive_Components/%5Ba%5D_z_tensioner_moving_moar_grip_x3_rev1.stl) exists, there should only be 4 copies needed, or 5 for 1 extra.
- [[a]_corner_motor_mount_2_piece_upper_x4_rev6.stl](https://github.com/Annex-Engineering/Gasherbrum-K3/blob/main/Release_1_2/STLs/XY_Gantry/%5Ba%5D_corner_motor_mount_2_piece_upper_x4_rev6.stl) and [corner_motor_mount_2_piece_upper_x4_rev4.stl](https://github.com/Annex-Engineering/Gasherbrum-K3/blob/main/Release_1_2/STLs/XY_Gantry/corner_motor_mount_2_piece_upper_x4_rev4.stl) share a name, despite serving entirely different functions.
- [x_max_split_corner_endstop_x2_rev3.stl](https://github.com/Annex-Engineering/Gasherbrum-K3/blob/main/Release_1_2/STLs/XY_Gantry/x_max_split_corner_endstop_x2_rev3.stl), [y_min_left_split corner_endstop_x1_rev4.stl](https://github.com/Annex-Engineering/Gasherbrum-K3/blob/main/Release_1_2/STLs/XY_Gantry/y_min_left_split%20corner_endstop_x1_rev4.stl), and [y_min_right_split corner_endstop_x1_rev4.stl](https://github.com/Annex-Engineering/Gasherbrum-K3/blob/main/Release_1_2/STLs/XY_Gantry/y_min_right_split%20corner_endstop_x1_rev4.stl) appear to be oriented incorrectly.

**Comment by Trails5000** [comment]
the 8 copies is intentional, some people have issues with them splitting or installing the inserts. Its minimal plastic and worth having spares

the rest are fixed
